### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jeevarg** [janaknpatel95/HotelWebsite#7]
# Design/Code Review 1

### Reviewer: Jeeva G

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 1, 3 - Problem statement has typos and there is room to improve on stating the problem more clearly. Typos in user stories as well.  |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Template looks good for the designs to be implemented. However, do not see a sign-in page in the screen desings. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| 2 - Not sure if Order table would be a proper entity in this model. I think booking / reservation would be more appropriate. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | 1, 2 - javadoc comments missing on some of the methods. |

**Comment by pawaitemadisoncollege** [comment]
@jeevarg Code-related comments could use improvement.  Did you find any printStackTrace statements or printlns? If so, please indicate where so @janaknpatel95   can easily fix them. If not, indicate none were found. Hint: the search feature is in Github can be useful for finding these. Classes sizes ok? Test Coverage?

**Comment by jeevarg** [comment]
Hi @janaknpatel95 , couple of print statements to be fixed in Database.java file @ lines 45, 48. Classes are sized OK. Test coverage looks good.
