### ISSUE TITLE
Design/Code Review 1

### ISSUE THREAD

**Issue by esajdak** [janaknpatel95/HotelWebsite#8]
# Design/Code Review 1
​
## Project: Hotel Website
​
### Developer: Janak
​
### Reviewer: Elizabeth
​
You're off to a great start, keep it up!

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Problem statement does a great job in describing what your project is for. I think it would be cool to think of something that really sets your hotel website apart from others beyond just cost, some additional feature that makes yours more attractive than the others. I would run through the readme and check for typos as well. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | I didn't see a mock up for your login page which may have just been forgotten about. The overall flow and screen designs make sense for typical things you'd want to do for a hotel website. The template looks great for your project. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Nice job implementing the connection between user and order. I think your order object may need some adjustments based on your project and the details you'll want to save for a reservation. May also consider renaming to reservation rather than order.   |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  | Implements the .gitignore. Most of your coding logic seems to make sense. Check spelling in directories as pointed out "hote" vs "hotel". Don't forget to include your javadocs. You're logging seems to be set up correctly. Nice job with the generic dao.  |

**Comment by pawaitemadisoncollege** [comment]
@esajdak Nice, thorough job with your review. Just one additional thing to check: Did you find any printStackTrace statements or printlns?
